### ISSUE TITLE
[docs] Readme file is not nice

### ISSUE THREAD

**Issue by c-moeller** [rl-institut/oemof-B3#3]
Explain in Readme, what oemof-B3 is about, add licence, logo and so on.

**Comment by jnnr** [comment]
Some text has been added. Still missing:

* [ ] License
* [ ] Logo (does not exist yet)

**Comment by monika-o** [comment]
The installation of the docs_requirements.txt following the readme file (on the dev branch) led to an error message:
`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /.../oemof-B3/docs`.

**Comment by MaGering** [comment]
> The installation of the docs_requirements.txt following the readme file (on the dev branch) led to an error message: `ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /.../oemof-B3/docs`. Do we need to install it in editable mode or could we remove that option from the docs_requirements.txt?

Good point! In order to fix this error I moved `docs_requirements.txt` to the parent directory and adapted `README.md` accordingly in https://github.com/rl-institut/oemof-B3/pull/128/commits/dc56254331409ea5894d12ea6b27724b8e4ab473 and https://github.com/rl-institut/oemof-B3/pull/128/commits/5bd4a52c9d083dce1274e332b360c810d6be3b06 in PR #128.

**Comment by jnnr** [comment]
The only open todo is adding a logo, which is nice to have.
