### ISSUE TITLE
Rule plot_all_resources stopped working

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#303]
Probably because the COLORS dictionary has changed (the keys are mapped to German/English) to match the labels.

**Comment by MaGering** [comment]
This is due to the file type being added twice in [this code](https://github.com/rl-institut/oemof-B3/blob/e33095a9216e5861d80134e87af18ba213dcf2ba/scripts/plot_conv_pp_scalars.py#L172) after file type has been introduced in settings.

The label issue is described here: https://github.com/rl-institut/oemof-B3/issues/328.
