### ISSUE TITLE
Bug: Bullet points in docs not rendered

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#61]
Seems to be a known issue, see here: https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

**Comment by MaGering** [comment]
Could you please add a link or description to the bullet points not rendered in the docs?

**Comment by jnnr** [comment]
Here, e.g.: https://oemof-b3.readthedocs.io/en/latest/getting_started.html#workflow-management-with-snakemake-separating-the-steps

**Comment by MaGering** [comment]
What I found out is, that the bug in issue https://github.com/readthedocs/sphinx_rtd_theme/issues/1115 was fixed with PR https://github.com/readthedocs/sphinx_rtd_theme/pull/1185 and merged into `sphinx_rtd_theme` master. However, the fix has not been released yet.

What I also noticed is that the [build](https://readthedocs.org/projects/oemof-b3/builds/14651629/) in `readthedocs` uses version `0.4.3`, which contains the bug.

See version for instance in latest build `Build #14651629`:
```
Collecting sphinx-rtd-theme<0.5
  Downloading sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl (6.4 MB)
```
Building the docs locally with version `0.5.2` doesn't lead to this bug. The bullet list is rendered correctly there.
I wonder if specifying the version of `sphinx-rtd-theme` to a version higher than `0.5.1` in `docs_requirements.txt` resolves this issue. Do you know if the version in this case also applies for the `readthedocs` build @jnnr?

**Comment by jnnr** [comment]
> I wonder if specifying the version of `sphinx-rtd-theme` to a version higher than `0.5.1` in `docs_requirements.txt` resolves this issue. Do you know if the version in this case also applies for the `readthedocs` build @jnnr?

Readthedocs uses the docs_requirements for its buillds, so yes, setting a version there could be a solution.

**Comment by jnnr** [comment]
@MaGering: Did you try to fix it by constraining the version?
